### ISSUE TITLE
add link to github.io to readme

### ISSUE THREAD

**Issue by thorade** [sjoelund/MLS-rst-spec#6]
Just an idea: Adding one of these links:
http://sjoelund.github.io/MLS-rst-spec/build/html/
http://sjoelund.github.io/MLS-rst-spec/build/singlehtml/
http://sjoelund.github.io/MLS-rst-spec/build/latex/ModelicaLanguageSpecification.pdf
to the ReadMe might help some people to find the generated output.

**Comment by sjoelund** [comment]
Fixed with 2a5c30feb56f1f9bf0ffa72c3870c56d1ec00e41 (link to readthedocs)

**Comment by thorade** [comment]
Even better. Thanks.

**Comment by dietmarw** [comment]
In that case it's probably better to remove the `gh-pages` branch again to avoid confusion.
